name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # List the files in the working directory after checkout
      - name: List files in the working directory (after checkout)
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files after checkout:"
          ls -alh $GITHUB_WORKSPACE

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-and-push-docker:
    needs: build-and-test  # This job depends on the previous job
    runs-on: ubuntu-latest

    steps:
      # Checkout the code again in this job
      - name: Checkout code
        uses: actions/checkout@v2  # Make sure the files are available for Docker build

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # List the files in the current directory before building the Docker image
      - name: List files before building Docker image
        run: |
          echo "Current working directory before Docker build:"
          pwd
          echo "Listing files before Docker build:"
          ls -alh

      # Build Docker image from the correct directory
      - name: Build Docker image
        run: |
          docker build -f $GITHUB_WORKSPACE/Dockerfile $GITHUB_WORKSPACE -t erisahalipaj2107/user-auth:latest

      - name: Push Docker image
        run: |
          docker push erisahalipaj2107/user-auth:latest

  restart-application:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Restart Application
        run: |
          ssh -i ${{ secrets.SSH_KEY }} user@${{ secrets.DROPLET_IP }} "docker-compose -f /path/to/docker-compose.yml up -d"
